"""Frame-precise script library for Celeste gameplay.

Each script is a list of (frame_offset, keys) pairs that replay
human-quality frame-precise inputs. Scripts are triggered by
Jev's situation recognition, not generated frame-by-frame.

This mirrors how speedrunners operate: recognize a pattern,
then execute a muscle-memory sequence.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from typing import Any

KEY_NAMES = ["up", "down", "left", "right", "z", "x", "c"]
KEY_BITS = {name: 1 << i for i, name in enumerate(KEY_NAMES)}


@dataclass
class FrameStep:
    """One frame's input state."""

    frame: int
    keys: list[str]

    @property
    def bitmask(self) -> int:
        mask = 0
        for k in self.keys:
            mask |= KEY_BITS.get(k, 0)
        return mask


@dataclass
class FrameScript:
    """A frame-precise input sequence for a specific gameplay situation.

    Example:
        FrameScript(
            id="dash_across_gap",
            name="Dash Across Gap",
            description="Jump then air-dash to cross a gap",
            steps=[
                FrameStep(0, ["right"]),
                FrameStep(4, ["right", "x"]),
                FrameStep(6, ["right"]),
                FrameStep(8, ["right", "z", "up"]),
                FrameStep(11, ["right"]),
                FrameStep(14, []),
            ],
            duration_frames=14,
            target_fps=60,
        )
    """

    id: str
    name: str
    description: str
    steps: list[FrameStep]
    duration_frames: int = 0
    target_fps: int = 60
    difficulty: str = "normal"  # easy / normal / hard / extreme
    prerequisites: list[str] = field(default_factory=list)  # e.g. ["has_dash", "airborne"]

    def __post_init__(self):
        if not self.duration_frames and self.steps:
            self.duration_frames = self.steps[-1].frame + 1

    @property
    def duration_seconds(self) -> float:
        return self.duration_frames / self.target_fps

    def get_input_at_frame(self, frame: int) -> list[str]:
        """Return the keys that should be pressed at a given frame."""
        active = FrameStep(frame, [])
        for step in self.steps:
            if step.frame <= frame:
                active = step
            else:
                break
        return active.keys

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "difficulty": self.difficulty,
            "duration_frames": self.duration_frames,
            "duration_seconds": round(self.duration_seconds, 3),
            "prerequisites": self.prerequisites,
            "steps": [
                {"frame": s.frame, "keys": s.keys} for s in self.steps
            ],
        }


class ScriptLibrary:
    """Manages frame-precise scripts indexed by situation ID.

    Scripts can be:
      - Pre-recorded from speedrun TAS tools
      - Manually authored from speedrun guides
      - Generated by DQN and cached (future)
    """

    # ── Built-in script collection ────────────────────────────

    BUILTIN_SCRIPTS: list[dict] = [
        {
            "id": "simple_move_right",
            "name": "Simple Move Right",
            "description": "Move right on flat ground",
            "difficulty": "easy",
            "steps": [
                {"frame": 0, "keys": ["right"]},
                {"frame": 30, "keys": []},
            ],
            "prerequisites": ["on_ground"],
        },
        {
            "id": "dash_across_gap",
            "name": "Dash Across Gap",
            "description": "Run, jump, then air-dash up-right to cross a gap",
            "difficulty": "normal",
            "steps": [
                {"frame": 0, "keys": ["right"]},
                {"frame": 4, "keys": ["right", "x"]},
                {"frame": 6, "keys": ["right"]},
                {"frame": 8, "keys": ["right", "z", "up"]},
                {"frame": 11, "keys": ["right"]},
                {"frame": 14, "keys": []},
            ],
            "prerequisites": ["has_dash"],
        },
        {
            "id": "wall_jump_climb",
            "name": "Wall Jump Climb",
            "description": "Grab wall, climb up, wall-jump to next surface",
            "difficulty": "hard",
            "steps": [
                {"frame": 0, "keys": ["left", "c"]},
                {"frame": 3, "keys": ["c"]},
                {"frame": 6, "keys": ["c", "up"]},
                {"frame": 20, "keys": ["c"]},
                {"frame": 22, "keys": ["c", "x"]},
                {"frame": 24, "keys": ["right"]},
                {"frame": 26, "keys": ["right", "z", "up"]},
                {"frame": 29, "keys": ["right"]},
                {"frame": 32, "keys": []},
            ],
            "prerequisites": ["near_wall"],
        },
        {
            "id": "spike_corridor_wait",
            "name": "Spike Corridor Wait",
            "description": "Wait for moving spikes to clear, then run through",
            "difficulty": "normal",
            "steps": [
                {"frame": 0, "keys": []},
                {"frame": 15, "keys": ["right"]},
                {"frame": 18, "keys": ["right", "x"]},
                {"frame": 20, "keys": ["right"]},
                {"frame": 25, "keys": []},
            ],
            "prerequisites": [],
        },
        {
            "id": "wave_dash_chain",
            "name": "Wave Dash Chain",
            "description": "Chain wave-dashes for maximum speed on flat ground",
            "difficulty": "extreme",
            "steps": [
                {"frame": 0, "keys": ["right", "x"]},
                {"frame": 2, "keys": ["right"]},
                {"frame": 3, "keys": ["right", "z", "down"]},
                {"frame": 5, "keys": ["right"]},
                {"frame": 6, "keys": ["right", "x"]},
                {"frame": 8, "keys": ["right"]},
                {"frame": 9, "keys": ["right", "z", "down"]},
                {"frame": 11, "keys": ["right"]},
                {"frame": 12, "keys": ["right", "x"]},
                {"frame": 14, "keys": ["right"]},
                {"frame": 15, "keys": ["right", "z", "down"]},
                {"frame": 17, "keys": ["right"]},
            ],
            "prerequisites": ["on_ground", "has_dash"],
        },
        {
            "id": "ceiling_dash_traverse",
            "name": "Ceiling Dash Traverse",
            "description": "Dash along ceiling to bypass floor spikes",
            "difficulty": "extreme",
            "steps": [
                {"frame": 0, "keys": ["up", "c"]},
                {"frame": 3, "keys": ["right", "z", "up"]},
                {"frame": 6, "keys": ["up", "c"]},
                {"frame": 9, "keys": ["right", "z", "up"]},
                {"frame": 12, "keys": ["up", "c"]},
                {"frame": 15, "keys": []},
            ],
            "prerequisites": ["on_ceiling", "has_dash"],
        },
        {
            "id": "strawberry_collect",
            "name": "Strawberry Collect",
            "description": "Approach strawberry, collect, and return to safe ground",
            "difficulty": "hard",
            "steps": [
                {"frame": 0, "keys": ["right"]},
                {"frame": 10, "keys": ["right", "x"]},
                {"frame": 12, "keys": ["right"]},
                {"frame": 15, "keys": []},
                {"frame": 30, "keys": ["left"]},
                {"frame": 40, "keys": ["left", "x"]},
                {"frame": 42, "keys": ["left"]},
                {"frame": 45, "keys": []},
            ],
            "prerequisites": [],
        },
        {
            "id": "rest_and_recover",
            "name": "Rest and Recover",
            "description": "Stand still on safe ground to recover stamina and plan next move",
            "difficulty": "easy",
            "steps": [
                {"frame": 0, "keys": []},
                {"frame": 60, "keys": []},
            ],
            "prerequisites": ["on_ground", "safe_spot"],
        },
        {
            "id": "hyper_jump",
            "name": "Hyper Jump",
            "description": "Down-dash then jump for burst speed",
            "difficulty": "hard",
            "steps": [
                {"frame": 0, "keys": ["z", "down"]},
                {"frame": 2, "keys": ["down"]},
                {"frame": 3, "keys": ["x", "right"]},
                {"frame": 5, "keys": ["right"]},
            ],
            "prerequisites": ["on_ground", "has_dash"],
        },
        {
            "id": "backtrack_left",
            "name": "Backtrack Left",
            "description": "Move left to find an alternate path",
            "difficulty": "easy",
            "steps": [
                {"frame": 0, "keys": ["left"]},
                {"frame": 30, "keys": []},
            ],
            "prerequisites": [],
        },
    ]

    def __init__(self, logger=None):
        self.logger = logger
        self._scripts: dict[str, FrameScript] = {}
        self._usage_stats: dict[str, int] = {}
        self._success_stats: dict[str, int] = {}
        self._load_builtin()

    def _load_builtin(self):
        for entry in self.BUILTIN_SCRIPTS:
            steps = [FrameStep(s["frame"], s["keys"]) for s in entry["steps"]]
            script = FrameScript(
                id=entry["id"],
                name=entry["name"],
                description=entry["description"],
                steps=steps,
                difficulty=entry.get("difficulty", "normal"),
                prerequisites=entry.get("prerequisites", []),
            )
            self._scripts[script.id] = script

    def add_script(self, script: FrameScript):
        self._scripts[script.id] = script

    def get(self, script_id: str) -> FrameScript | None:
        return self._scripts.get(script_id)

    def list_scripts(self) -> list[str]:
        return list(self._scripts.keys())

    def get_options_for_jev(self) -> dict[str, str]:
        """Return script IDs and descriptions for Jev's Choice question."""
        return {
            sid: f"{s.name}: {s.description}"
            for sid, s in self._scripts.items()
        }

    def record_usage(self, script_id: str, success: bool):
        self._usage_stats[script_id] = self._usage_stats.get(script_id, 0) + 1
        if success:
            self._success_stats[script_id] = self._success_stats.get(script_id, 0) + 1

    def get_stats(self) -> dict[str, Any]:
        stats = {}
        for sid in self._scripts:
            uses = self._usage_stats.get(sid, 0)
            succ = self._success_stats.get(sid, 0)
            stats[sid] = {
                "uses": uses,
                "successes": succ,
                "success_rate": succ / uses if uses > 0 else 0,
            }
        return stats

    def export_json(self) -> str:
        data = [s.to_dict() for s in self._scripts.values()]
        return json.dumps(data, indent=2, ensure_ascii=False)
